//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePontoAM.Models.ADO.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastrohora
    {
        public int codigo { get; set; }
        public int codigo_usuario { get; set; }
        public string horaEntradaInicio { get; set; }
        public string horaSaidaInicio { get; set; }
        public string horaEntradaTarde { get; set; }
        public string horaSaidaTarde { get; set; }
        public string observacao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string dia { get; set; }
        public string mes { get; set; }
        public string ano { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
