//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlePontoAM.Models.ADO.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlePontoEntities2 : DbContext
    {
        public ControlePontoEntities2()
            : base("name=ControlePontoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cadastrohora> cadastrohora { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }

        public System.Data.Entity.DbSet<cadastrohora> cadastrohoras { get; set; }
    }
}
